[[plugins]]
repo = 'shaunsingh/nord.nvim'
hook_add = '''
let g:nord_contrast = v:true
let g:nord_borders = v:true
"let g:nord_disable_background = v:true
let g:nord_cursorline_transparent = v:true
'''

[[plugins]]
repo = 'Shatur/neovim-ayu'
hook_add = 'lua require("ayu").setup({});'


