[[plugins]]
repo = 'shaunsingh/nord.nvim'
hook_add = 'lua require("dein.nord");'

[[plugins]]
repo = 'Shatur/neovim-ayu'
hook_add = 'lua require("ayu").setup({});'

[[plugins]]
repo = 'taiton-k/winter-night.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'rebelot/kanagawa.nvim'
hook_add = 'lua require("dein.kanagawa");'
