[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'shaunsingh/nord.nvim'
hook_add = '''
let g:nord_contrast = v:true
let g:nord_borders = v:true
"let g:nord_disable_background = v:true
let g:nord_cursorline_transparent = v:true
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
hook_add = 'lua require("dein.indent_blankline");'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/pum.vim'
hook_add = 'call pum#set_option( "border","rounded")'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = 'lua require("dein.ddc");'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-matcher_length'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'tani/ddc-fuzzy'
