[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
hook_add = 'lua require("dein.indent_blankline");'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = 'lua require("dein.treesitter");'
hook_post_update = 'TSUpdate'

[[plugins]]
repo =  'neovim/nvim-lspconfig'
hook_add = 'lua require("dein.lspconfig");'

#[[plugins]]
#repo = 'skanehira/jumpcursor.vim'
#hook_add = 'map <Leader>j <Plug>(jumpcursor-jump)'

[[plugins]]
repo = 'taiton-k/flterm.lua'
hook_add = 'lua require("dein.flterm");'

[[plugins]]
#repo = 'zah/nim.vim'
repo = 'alaviss/nim.nvim'

[[plugins]]
repo = 'tikhomirov/vim-glsl'



[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/pum.vim'
hook_add = 'lua require("dein.pum");'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = 'lua require("dein.ddc");'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-matcher_length'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'

[[plugins]]
repo = 'Shougo/ddc-line'

#[[plugins]]
#repo = 'gamoutatsumi/ddc-emoji'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'tani/ddc-fuzzy'



[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = 'lua require("dein.ddu")'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-kind-word'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-line'

[[plugins]]
repo = 'shun/ddu-source-buffer'

#[[plugins]]
#repo = 'gamoutatsumi/ddu-source-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'matsui54/ddu-source-help'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_relative'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
