## パッケージマネージャ
[[plugins]]
repo = 'Shougo/dein.vim'

## インデント
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
hook_add = "lua require('conf/indent')"

## ウィンドウのリサイズを簡単にする
[[plugins]]
repo = 'simeji/winresizer'

## 色
[[plugins]]
repo = 'guns/xterm-color-table.vim'

## ヘルプを日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja,en'



###### ファイラー

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_source = '''
runtime conf/nvim-tree.vim
lua require('conf/nvim-tree')
'''

[[plugins]]
repo = 'kevinhwang91/rnvimr'

###########
