################################## ステータスバー & タブバー
#[[plugins]]
#repo = 'adelarsq/neoline.vim'

#[[plugins]]
#repo = 'beauwilliams/statusline.lua'

#[[plugins]]
#repo = 'datwaft/bubbly.nvim'

#[[plugins]]
#repo = 'hoob3rt/lualine.nvim'
#hook_add = "lua require('nvim-lualine')"

#[[plugins]]
#repo = 'jose-elias-alvarez/buftabline.nvim'
#hook_add = "lua require('nvim-buftabline')"

#[[plugins]]
#repo = 'crispgm/nvim-tabline'
#hook_add = "lua require('nvim-tabline')"

#[[plugins]]
#repo = 'ojroques/nvim-bufbar'
#hook_add = "lua require('nvim-bufber')"

#[[plugins]]
#repo = 'romgrk/barbar.nvim'

#[[plugins]]
#repo = 'noib3/cokeline.nvim'
#hook_add = "lua require('nvim-cokeline')"




#[[plugins]]
#repo = 'tyru/eskk.vim'
#on_event = 'InsertEnter'
#hook_source = 'runtime dein/conf/eskk.vim'


#[[plugins]]
#repo = 'Yggdroot/indentLine'
#hook_add = 'runtime dein/conf/indentLine.vim'

