## 組み込みLSP
[[plugins]]
repo =  'neovim/nvim-lspconfig'
on_ft = ['cpp','vim','lua']
hook_source = 'runtime dein/conf/nvim-lspconfig.lua'

## Denoを使えるようにする
[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'InsertEnter'



####### ddc.vim 関連

## PopUp Menu  .vim
[[plugins]]
repo = 'Shougo/pum.vim'

# 新手の補完プラグイン
[[plugins]]
repo = 'Shougo/ddc.vim'
on_source = 'denops.vim'
depends = ['denops.vim']
hook_source = 'runtime dein/conf/ddc.vim'
hook_add = 'runtime dein/conf/ddc_cmd.vim'

# ddc.vim のLSP補完ソース
[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'
depends = ['ddc.vim','nvim-lspconfig']

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'
depends = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-matcher_length'
on_source = 'ddc.vim'
depends = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'
depends = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'
depends = ['ddc.vim']

# ファイルの補完ソース
[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'
depends = ['ddc.vim']

# Vim Script の補完ソース
[[plugins]]
repo = 'Shougo/neco-vim'
on_source = 'ddc.vim'
depends = ['ddc.vim']

# コマンドライン履歴の補完ソース
[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = 'ddc.vim'
depends = ['ddc.vim']

# 被った候補を消してくれる
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'
depends = ['ddc.vim']


#######



## シンタックスハイライトをすごくしてくれる奴
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_ft = ['cpp','vim','lua']
hook_source = 'runtime dein/conf/nvim-treesitter.lua'
hook_post_update = 'TSUpdate'

## Nyan Cat
[[plugins]]
repo = 'koron/nyancat-vim'
on_event = 'InsertEnter'

## Tomlファイルのシンタックスハイライトプラグイン
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

## SKKを使えるようにする
[[plugins]]
repo = 'vim-skk/denops-skkeleton.vim'
on_source = 'denops.vim'
hook_source = 'runtime dein/conf/skkeleton.vim'
depends = ['denops.vim']

## 括弧を補完してくれるすごいやつ
[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'
hook_source = 'runtime dein/conf/autopairs.lua'

###### デバッグできるようにしてくれる奴
[[plugins]]
repo = 'mfussenegger/nvim-dap'
on_ft = ['cpp']
hook_source = 'runtime dein/conf/nvim-dap.lua'

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
on_source = 'nvim-dap'
depends = ['nvim-dap']

[[plugins]]
repo = 'theHamsta/nvim-dap-virtual-text'
on_source = 'nvim-dap'
depends = ['nvim-dap']

#####


####### Markdown

## Markdownをプレビューできる奴
[[plugins]]
repo = 'kat0h/bufpreview.vim'
on_ft = ['markdown']
depends = ['denops.vim']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

#####
